let products = [
  {
    id: 0,
    name: "هنگ درام چوپی مدل زحل سرمه ای",
    price: 13200000,
    inStock: 3,
    imgSrc: "img/1.png",
  },
  {
    id: 1,
    name: "پیانو دیجیتال Roland RP 701",
    price: 78000000,
    inStock: 5,
    imgSrc: "img/2.png",
  },
  {
    id: 2,
    name: "سه تار عظیمی 17 ترک پنجه قنبری",
    price: 4400000,
    inStock: 4,
    imgSrc: "img/3.png",
  },
  {
    id: 3,
    name: "عود خانی حرفه ای",
    price: 7000000,
    inStock: 1,
    imgSrc: "img/4.png",
  },
  {
    id: 4,
    name: "ویولن والنسیا 1/4",
    price: 3900000,
    inStock: 2,
    imgSrc: "img/5.png",
  },
  {
    id: 5,
    name: "ESP LTD M-1001 See Thru – Black",
    price: 59900000,
    inStock: 3,
    imgSrc: "img/6.png",
  },
  {
    id: 6,
    name: "image.png",
    price: 1900000,
    inStock: 1,
    imgSrc: "img/7.png",
  },
  {
    id: 7,
    name: "ست تومبا و بانگو Pearl مدل Havana Series",
    price: 142910000,
    inStock: 3,
    imgSrc: "img/8.png",
  },
];
